### ISSUE TITLE
Escaping

### ISSUE THREAD

**Issue by stepankobzey** [sjdirect/nrobots#1]
when robots.txt contains entry like this:
Disallow:
https://www.overstock.com/cgi-bin/d2.cgi?SEC_IID=27592&PAGE=MYACCOUNT

than disallow entry is https://www.overstock.com/ and basically its skips all the urls

Robots.cs line 361

**Comment by sjdirect** [comment]
Both of these issues are now fixed an checked in with https://github.com/sjdirect/nrobots/commit/6e4134f0e253a9c12c800ec3ce1ef0b137312b46
